[14.0] Shopfloor mobile base auth api key - move logic to handler
camptocamp/wms pull request #108
Opened 2021-10-28 15:54 UTC by JuMiSanAr

Refactor to move the api_key logic logic to the handler:

- Add on_login and on_logout methods in the api_key handler.
- Refactor _on_login method in $root.
- Refactor handling of different error messages depending on auth type.

2021-10-28 16:06 UTC, simahawk requested changes

2021-10-28 16:06 UTC, simahawk commented on shopfloor_mobile_base_auth_api_key/static/wms/src/login.js
> +                if (!$root.authenticated) {
```suggestion
                if (!$root.is_authenticated()) {
```

2021-10-28 16:06 UTC, simahawk commented on shopfloor_mobile_base_auth_api_key/static/wms/src/login.js
> +        const def = $.Deferred();
you don't need this func

2021-10-28 16:06 UTC, simahawk commented on shopfloor_mobile_base_auth_api_key/static/wms/src/login.js
> +                return def.reject("screen.login.error.api_key_invalid");
this is wrong: you are returning the translation key, not the translation itself
```suggestion
                return def.reject($root.$("screen.login.error.api_key_invalid"));
```

2021-10-28 16:06 UTC, simahawk commented on shopfloor_mobile_base_auth_api_key/static/wms/src/login.js
> +            ._loadConfig()
isn't the root that calls _loadConfig now?

2021-10-28 16:06 UTC, simahawk commented on shopfloor_mobile_base_auth_api_key/static/wms/src/login.js
> +        $root.apikey = data.apikey;
I don't think you need any login, the api key can be stored before and then you are done because of the header from the handler

2021-10-29 09:28 UTC, JuMiSanAr commented on shopfloor_mobile_base/static/wms/src/main.js
> +            evt.preventDefault();
The "Invalid credentials" message disappeared as the page refreshed, so I added preventDefault back.

2021-11-02 08:59 UTC, simahawk approved these changes

2021-11-02 08:59 UTC, simahawk commented on shopfloor_mobile_base/static/wms/src/loginpage.js
> +            this.error = this.$root.$t("screen.login.error.login_invalid");
this is not needed as all the components have `$t` available

2021-11-02 09:00 UTC, merged